### ISSUE TITLE
To-Do List for Community Events 5

### ISSUE THREAD

**Issue by TechpriestEnginseer** [TechpriestEnginseer/Community-Patch-Events-Development#67]
- [x] Work natural wonders (dont forget to set it to an event type and add audio for them)...
If you want to see the update I made on Natural Wonders see here.
https://civ-5-cbp.wikia.com/wiki/Natural_Wonder_Events
Most noticable nerf is that I've removed the Golden Age Point since that just made them more powerful for no apparent reason.
- [ ] Advisor Rework
 Player Events for the Advisors are now obsoleted until further notice.
For more changelog here see https://civ-5-cbp.wikia.com/wiki/Advisor_Events
- [x] Civilization Events that grant free Great Person now available at Renaissance Era instead of Medieval Era.
- [x] Balance America.
Manifest Destiny's Bonus now applies to Pastures.
Veteran Pensions now grants +2 Horses.
Veteran Pensions now grant its bonuses to Pastures as well.
- [x] Balance Arabia.
Reduced Religious Institution's culture cost from 250 to 200.
Religious Authority now consumes a scaled portion of Golden Age Points rather than Culture.
- [x] Balance Aztec
Conquer Philosophy now grants 5 Golden Age Point scaling with City and Era everytime a policy is unlocked.
- [x] Balance Byzantium
Foreign Mercenaries now require 50 Gold scaling per era instead of 150 Gold. They also do not require horses since the unit they spawn don't require horses.
- [x] Brazil Fix for their GP Event not granting a GP.
- [x] Balance Denmark
Longhouses also adds +1 Production to the Barrack.
- [x] Balance Inca
Alpaca Wool now grants +2 Happiness.
- [x] Balance Indonesia
Sea Trade reduced from 200 Culture to 100 Culture.
- [x] Balance Iroquois
Wampum Industry now requires 1000 Culture and 1000 Golden Age Points instead of 2000 Culture.
- [x] Balance Rome
Thermae no longer needs a scaling amount of 300 Science and 150 Gold to be used.
Mayor of the Palace's free Envoys upgraded to Diplomats.
Mayor of the Palace now grants +1 Happiness in the Palace.
- [x] Have to fix needs modifiers for unique event religious buildings and event choices... >:(
This is actually more work than the rest of these list implies.
- [x] Quite the Rug nerf (50 BGP and Tourism no longer scales with era)
- [x] Fixed Contraband Smuggler tooltip.
- [x] Fixed War Material granting 3 Envoys per City rather than just the Capital.
- [x] Olympic Game where it grants you a free emissary can only be chosen if you have a Scrivener's Office. The event now expires at Renaissance Era instead of Medieval Era.
- [x] Reduced Firework's Happiness from 2 to 1, but increased Firework's Duration from 5 to 10.
- [x] Removed one of the choices of The Notorious Pirate... I forgot what it was.
- [ ] Added a Philosophical Thought event (Grants +2 Science and +2 Culture in a city with the School of Philosophy for 10 Turns).
- [ ] Added a Drying Lands (-4 Food in the City for 15 Turns to scale per era)
- [ ] Added a Fertile Soil (+4 Food in the City for 15 Turns scaling per era)
- [ ] Added a Brilliant Architect (+50 Production in the City)
- [ ] Added a Theoretical Architect (-50 Production in the City)
- [ ] Added an Inheritance to the State (+500 Gold scaling per Era)
- [ ] Added a Lawsuit to the State (Negative gold if you don't do anything but something about E&D-related stuff should mitigate this once E&D is updated)
- [ ] Added Eureka! (+50 Science scaling per Era)
- [ ] Added Pointless Funding (-50 Science scaling per Era)
- [ ] Added a Role Model (+2 Culture in the City for 50 Turns scaling per era)
- [ ] Added Forgotten Histories (-25 Culture in the City scaling per era)
- [ ] Added A Lost Relic (+2 Faith in the City for 50 Turns scaling per era)
- [ ] Added Religious Persecution (unless you're spain, have a candi, or have a pagoda... -2 Faith in the City)
- [ ] Added Greatness on the Trees (+5 Tourism in the City for 30 Turns)
- [ ] Added Degenerate Society (-10 Tourism in the City for 30 Turns)
- [ ] A Heroic Progress (+50 Golden Age Points scaling per era)
- [ ] A Dark Progress (-50 Golden Age Points scaling per era)
- [ ] Anti-War Rhetoric (-50 Great General Point and -50 Great Admiral Points)
- [ ] Leadership Inspires All (+50 Great General Point)
- [ ] Pardon Pirates (+50 Great Admiral Points)
- [ ] Explorers of the Water (May recruit a Barbarian Galley to your cause through Food, or Gold)
- [ ] Unite the Tribes (Brutes/Throwing Axemans may appear near your Capital as allies)
- [ ] Boom of Babies (+1 Population)
- [ ] Destined Prerogative (+50 Border Growth Point)
- [x] Investigate bank event
- [x] Fixed an assination with foreign ppl?
- [x] Fixed theocratic event and civil servants bug
- [x] Nerfed Barbarian Hordes
You no longer get a free unit for the ancient horde. Number of barbarian spawned reduced from 3 to 2. Now you also need to hold 300 Gold or more in your treasury because the barbarian horde won't bother with such a poor city.
Medieval Horde and Industrial Horde however are indifferent to your economic situation for they are your own people!
Medieval Horde's numbers of barbarian reduced from 4 to 3.
Industrial Horde's Resistance reduced from 4 to 2.

**Comment by TechpriestEnginseer** [comment]
Writer's Guilds
Artist's Guilds
Musician's Guilds

These guilds will all contribute to an event pool of a set of Cultural Events sparking a global movement across all Civilizations.

Writers contribute to a pool of Writing Genres.
Artists contribute to a pool of Cultural Movements.
Musicians contribute to a pool of Music Types.
