### ISSUE TITLE
To-Do List for Community Events 6

### ISSUE THREAD

**Issue by TechpriestEnginseer** [TechpriestEnginseer/Community-Patch-Events-Development#68]
Maybe for Version 6...
- [ ] A Tribe of the North (European Mercenaries arrive at your disposal) [May expend gold for purchasing unique units at a much higher cost {150% tot heir gold cost}]
- [ ] A Tribe of the West (Greco-Romans Mercenaries arrive at your disposal) [May expend gold for purchasing unique units at a much higher cost {150% to their gold cost}]
- [ ] A Tribe of the South (African Mercenaries arrive at your disposal) [May expend gold for purchasing unique units at a much higher cost {150% tot heir gold cost}]
- [ ] A Tribe of the East (Asian Mercenaries arrive at your disposal) [May expend gold for purchasing unique units at a much higher cost {150% to their gold cost}]
- [ ] A Tribe of the Water (Polynesian Mercenaries arrive at your disposal) [May expend gold for purchasing unique units at a much higher cost {150% to their gold cost}]
- [ ] A Tribe of the Distant (South American Mercenaries arrive at your disposal) [May expend gold for purchasing unique units at a much higher cost {150% to their gold cost}]
- [ ] Added a fully developed writing system (Unlocks Writing for free) [very rare tho]
- [ ] Zero and One System (Unlocks Mathematics for free) [very rare tho]
- [ ] The Hero of {Cityname} (Free Great Scientist) [very rare tho]
